my_page_edit: my_page_edit.o keyboard.o xterm_control.o
	gcc my_page_edit.o keyboard.o xterm_control.o -o my_page_edit
	
my_page_edit.o: my_page_edit.c
	gcc -c my_page_edit.c
	
keyboard.o:     keyboard.c
	gcc -c keyboard.c
	
xterm_control.o:        xterm_control.c
	gcc -c xterm_control.c
	